"""Make an offline producer/reuser planning report from frozen results."""
import html,json,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
e=html.escape
LABELS={'same-definition':'Original endpoint','forward-origin':'Change time origin','death-classification':'Change death-event rule','therapy-cutoff':'Add therapy cutoff'}
def main():
 d=json.loads((ROOT/'innovation/results.json').read_text());v=json.loads((ROOT/'innovation/solver-verification.json').read_text());out=ROOT/'demo/planning';out.mkdir(exist_ok=True)
 table='<tr><th>Proposed release</th>'+''.join('<th>'+e(v)+'</th>' for v in LABELS.values())+'</tr>'
 for r in d['producer_release_matrix']:
  table+='<tr><th>'+e(r['release'])+'</th>'
  for k in LABELS:
   ok=r['questions'][k]['status']=='determined_in_model';table+='<td class="'+('yes' if ok else 'no')+'">'+('Determined' if ok else 'Ambiguous')+'</td>'
  table+='</tr>'
 cards=[]
 for r in d['requests']:
  q=r['request'];ms=r['frontier']['minimal_supplements'];body=''.join('<li>'+e(', '.join(m['additional_components']) or 'No supplement needed')+'</li>' for m in ms)
  if not ms:body='<li>No sufficient supplement in the declared candidate set</li>'
  cards.append('<article><h3>'+e(q['id'].replace('-',' ').capitalize())+'</h3><p><b>Already shared:</b> '+e(', '.join(q['available_components']))+'</p><p><b>Additional information options:</b></p><ul>'+body+'</ul><p class="muted">'+e(q['expert_baseline'])+'</p><details><summary>Inspect assumptions, candidates and synthetic evidence</summary><pre>'+e(json.dumps(r,indent=2))+'</pre></details></article>')
 assumptions=''.join('<li>'+e(x)+'</li>' for x in d['model_assumptions'])
 s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Which research questions survive sharing?</title><style>
*{box-sizing:border-box}body{margin:0;background:#eff4f1;color:#173c45;font:16px/1.55 system-ui}header{background:#153f48;color:white;padding:40px max(24px,calc((100vw - 1100px)/2))}h1{font-size:clamp(30px,4vw,48px);line-height:1.12;margin:16px 0}header p{max-width:870px}main{max-width:1148px;margin:auto;padding:24px}.tag{color:#a4e3d2;font-size:13px;letter-spacing:1px}a{color:#086e61}header a{color:#a4e3d2}.table-wrap{overflow-x:auto;background:white;border-radius:9px;padding:12px}table{border-collapse:collapse;width:100%;min-width:680px}th,td{padding:13px;text-align:left;border-bottom:1px solid #d3e0da}th{font-size:14px}.yes{color:#126454;background:#e0f1e7}.no{color:#89522c;background:#fff0e3}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}article,.scope{padding:22px;background:white;border:1px solid #ccddd4;border-radius:9px}article h3{margin-top:0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}summary{cursor:pointer;color:#086e61}.muted{color:#53696e;font-size:14px}.scope{margin:24px 0;border-left:5px solid #bb7b39}li{overflow-wrap:anywhere}footer{margin:28px 0}@media(max-width:700px){.cards{grid-template-columns:1fr}main{padding:16px}article{padding:17px}}
</style><header><div class="tag">CANCER REUSE DECISION CONTRACTS / INFORMATION PLANNING</div><h1>Which research questions<br>survive sharing?</h1><p>Compare proposed endpoint releases, then inspect the additional information needed for a different analysis. These results apply within the stated model. Every example is synthetic.</p><a href="../index.html">Open the recorded-decision examples</a></header><main><h2>Compare four release designs</h2><p>Determined means histories agreeing on the shared information also agree on the target result, within this model. Ambiguous means a pair of histories demonstrates a different target result.</p><div class="table-wrap"><table>'''+table+'''</table></div><section class="scope"><b>Use this as planning evidence.</b> Review the source definition and chronology assumptions before requesting a supplement or choosing a release. This report does not validate a clinical endpoint, authorize disclosure, or approve an analysis. Smaller field counts do not establish lower privacy risk. The planner does not automatically change a recorded decision.</section><h2>Find sufficient supplements</h2><p>Each displayed option is inclusion-minimal among the named candidates: removing any of its components leaves ambiguity. Different options can have different sizes. A complete result is limited to this candidate universe and model.</p><div class="cards">'''+''.join(cards)+'''</div><h2>Inspect the model</h2><ul>'''+assumptions+'''</ul><h2>Replayable evidence</h2><p>Seven mechanism requests, 16 release/question checks, 640 derivation comparisons and '''+str(v['distinct_obligations'])+''' saved checks agreed across Z3 and cvc5. These are technical controls, not a user study. Source code, requests and solver inputs are in the review package.</p><footer><a href="results.json">Full results and implementation hashes</a> | <a href="solver-verification.json">Second-solver verification</a></footer></main></html>'''
 (out/'index.html').write_text(s,encoding='utf-8');shutil.copy2(ROOT/'innovation/results.json',out/'results.json');shutil.copy2(ROOT/'innovation/solver-verification.json',out/'solver-verification.json')
if __name__=='__main__':main()
